export const teams = [
    { name: "Arizona Cardinals", logo: "./path/to/cardinals-logo.png", id: 1 },
    { name: "Atlanta Falcons", logo: "./path/to/falcons-logo.png", id: 2 },
    { name: "Baltimore Ravens", logo: "./path/to/ravens-logo.png", id: 3 },
    { name: "Buffalo Bills", logo: "./path/to/bills-logo.png", id: 4 },
    { name: "Carolina Panthers", logo: "./path/to/panthers-logo.png", id: 5 },
    { name: "Chicago Bears", logo: "./path/to/bears-logo.png", id: 6 },
    { name: "Cincinnati Bengals", logo: "./path/to/bengals-logo.png", id: 7 },
    { name: "Cleveland Browns", logo: "./path/to/browns-logo.png", id: 8 },
    { name: "Dallas Cowboys", logo: "./path/to/cowboys-logo.png", id: 9 },
    { name: "Denver Broncos", logo: "./path/to/broncos-logo.png", id: 10 },
    { name: "Detroit Lions", logo: "./path/to/lions-logo.png", id: 11 },
    { name: "Green Bay Packers", logo: "./path/to/packers-logo.png", id: 12 },
    { name: "Houston Texans", logo: "./path/to/texans-logo.png", id: 13 },
    { name: "Indianapolis Colts", logo: "./path/to/colts-logo.png", id: 14 },
    { name: "Jacksonville Jaguars", logo: "./path/to/jaguars-logo.png", id: 15 },
    { name: "Kansas City Chiefs", logo: "./path/to/chiefs-logo.png", id: 16 },
    { name: "Las Vegas Raiders", logo: "./path/to/raiders-logo.png", id: 17 },
    { name: "Los Angeles Chargers", logo: "./path/to/chargers-logo.png", id: 18 },
    { name: "Los Angeles Rams", logo: "./path/to/rams-logo.png", id: 19 },
    { name: "Miami Dolphins", logo: "./path/to/dolphins-logo.png", id: 20 },
    { name: "Minnesota Vikings", logo: "./path/to/vikings-logo.png", id: 21 },
    { name: "New England Patriots", logo: "./path/to/patriots-logo.png", id: 22 },
    { name: "New Orleans Saints", logo: "./path/to/saints-logo.png", id: 23 },
    { name: "New York Giants", logo: "./path/to/giants-logo.png", id: 24 },
    { name: "New York Jets", logo: "./path/to/jets-logo.png", id: 25 },
    { name: "Philadelphia Eagles", logo: "./path/to/eagles-logo.png", id: 26 },
    { name: "Pittsburgh Steelers", logo: "./path/to/steelers-logo.png", id: 27 },
    { name: "San Francisco 49ers", logo: "./path/to/49ers-logo.png", id: 28 },
    { name: "Seattle Seahawks", logo: "./path/to/seahawks-logo.png", id: 29 },
    { name: "Tampa Bay Buccaneers", logo: "./path/to/buccaneers-logo.png", id: 30 },
    { name: "Tennessee Titans", logo: "./path/to/titans-logo.png", id: 31 },
    { name: "Washington Commanders", logo: "./path/to/commanders-logo.png", id: 32 }
];