export const teams = [
    { name: "Arizona Cardinals", logo: "https://upload.wikimedia.org/wikipedia/en/7/72/Arizona_Cardinals_logo.svg", id: 1 },
    { name: "Atlanta Falcons", logo: "https://upload.wikimedia.org/wikipedia/en/c/c5/Atlanta_Falcons_logo.svg", id: 2 },
    { name: "Baltimore Ravens", logo: "https://upload.wikimedia.org/wikipedia/en/1/16/Baltimore_Ravens_logo.svg", id: 3 },
    { name: "Buffalo Bills", logo: "https://upload.wikimedia.org/wikipedia/en/7/77/Buffalo_Bills_logo.svg", id: 4 },
    { name: "Carolina Panthers", logo: "https://upload.wikimedia.org/wikipedia/en/1/1c/Carolina_Panthers_logo.svg", id: 5 },
    { name: "Chicago Bears", logo: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Chicago_Bears_logo.svg", id: 6 },
    { name: "Cincinnati Bengals", logo: "https://upload.wikimedia.org/wikipedia/commons/8/81/Cincinnati_Bengals_logo.svg", id: 7 },
    { name: "Cleveland Browns", logo: "https://upload.wikimedia.org/wikipedia/en/d/d9/Cleveland_Browns_logo.svg", id: 8 },
    { name: "Dallas Cowboys", logo: "https://upload.wikimedia.org/wikipedia/commons/1/15/Dallas_Cowboys.svg", id: 9 },
    { name: "Denver Broncos", logo: "https://upload.wikimedia.org/wikipedia/en/4/44/Denver_Broncos_logo.svg", id: 10 },
    { name: "Detroit Lions", logo: "https://upload.wikimedia.org/wikipedia/en/7/71/Detroit_Lions_logo.svg", id: 11 },
    { name: "Green Bay Packers", logo: "https://upload.wikimedia.org/wikipedia/commons/5/50/Green_Bay_Packers_logo.svg", id: 12 },
    { name: "Houston Texans", logo: "https://upload.wikimedia.org/wikipedia/en/2/28/Houston_Texans_logo.svg", id: 13 },
    { name: "Indianapolis Colts", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Indianapolis_Colts_logo.svg/100px-Indianapolis_Colts_logo.svg.png", id: 14 },
    { name: "Jacksonville Jaguars", logo: "https://upload.wikimedia.org/wikipedia/en/7/74/Jacksonville_Jaguars_logo.svg", id: 15 },
    { name: "Kansas City Chiefs", logo: "https://upload.wikimedia.org/wikipedia/en/e/e1/Kansas_City_Chiefs_logo.svg", id: 16 },
    { name: "Las Vegas Raiders", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/4/48/Las_Vegas_Raiders_logo.svg/100px-Las_Vegas_Raiders_logo.svg.png", id: 17 },
    { name: "Los Angeles Chargers", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Los_Angeles_Chargers_logo.svg/100px-Los_Angeles_Chargers_logo.svg.png", id: 18 },
    { name: "Los Angeles Rams", logo: "https://upload.wikimedia.org/wikipedia/en/8/8a/Los_Angeles_Rams_logo.svg", id: 19 },
    { name: "Miami Dolphins", logo: "https://upload.wikimedia.org/wikipedia/en/3/37/Miami_Dolphins_logo.svg", id: 20 },
    { name: "Minnesota Vikings", logo: "https://upload.wikimedia.org/wikipedia/en/4/48/Minnesota_Vikings_logo.svg", id: 21 },
    { name: "New England Patriots", logo: "https://upload.wikimedia.org/wikipedia/en/b/b9/New_England_Patriots_logo.svg", id: 22 },
    { name: "New Orleans Saints", logo: "https://upload.wikimedia.org/wikipedia/commons/5/50/New_Orleans_Saints_logo.svg", id: 23 },
    { name: "New York Giants", logo: "https://upload.wikimedia.org/wikipedia/commons/6/60/New_York_Giants_logo.svg", id: 24 },
    { name: "New York Jets", logo: "https://upload.wikimedia.org/wikipedia/en/6/6b/New_York_Jets_logo.svg", id: 25 },
    { name: "Philadelphia Eagles", logo: "https://upload.wikimedia.org/wikipedia/en/8/8e/Philadelphia_Eagles_logo.svg", id: 26 },
    { name: "Pittsburgh Steelers", logo: "https://upload.wikimedia.org/wikipedia/commons/d/de/Pittsburgh_Steelers_logo.svg", id: 27 },
    { name: "San Francisco 49ers", logo: "https://upload.wikimedia.org/wikipedia/commons/3/3a/San_Francisco_49ers_logo.svg", id: 28 },
    { name: "Seattle Seahawks", logo: "https://upload.wikimedia.org/wikipedia/en/8/8e/Seattle_Seahawks_logo.svg", id: 29 },
    { name: "Tampa Bay Buccaneers", logo: "https://upload.wikimedia.org/wikipedia/en/a/a2/Tampa_Bay_Buccaneers_logo.svg", id: 30 },
    { name: "Tennessee Titans", logo: "https://upload.wikimedia.org/wikipedia/en/c/c1/Tennessee_Titans_logo.svg", id: 31 },
    { name: "Washington Commanders", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Washington_Commanders_logo.svg/100px-Washington_Commanders_logo.svg.png", id: 32 }
];